### PR TITLE
updating schema names to rename *-test to  *_test

### PR DESCRIPTION
**Pull request by rcordeau**
This change is [Reviewable](https://reviewable.io/reviews/smarterapp/rdw_schema/64)

### CODE REVIEW

**Comment by agorina** [comment]
There are a lot of places in the migrate code that has this hardcoded.
We need to do a 'find a replace' for all of them once it is done.
Let's talk how we want to coordinate it.

**Comment by rcordeau** [comment]
If you are talking about the migrate code in Ingest, I have already gone through and replaced it all and ran the integration tests against these changes.  I won't merge this PR until you see that code. We can go over it today.

**Comment by agorina** [comment]
I just submitted another review that added may more..

**Comment by rcordeau** [comment]
Ok, no problem. I'll get that one too. :-)

**Comment by agorina** [comment]
Thank you. 
Let's coordinate the timing since Chris and I are working on adding more.

**Pull request merged**
